/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Thesis;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void testMain() {
        assertTrue(true);
    }
}
